all: declaration_of_variables initialization_of_variables introduction_to_strings

declaration_of_variables: declaration_of_variables.cpp
	g++ -std=c++0x declaration_of_variables.cpp -o declaration_of_variables

initialization_of_variables: initialization_of_variables.cpp
	g++ -std=c++0x initialization_of_variables.cpp -o initialization_of_variables

introduction_to_strings: introduction_to_strings.cpp
	g++ -std=c++0x introduction_to_strings.cpp -o introduction_to_strings


clean:
	rm declaration_of_variables initialization_of_variables introduction_to_strings
