all: assignment_operator compound_assignment conditional_ternary_operator

assignment_operator: assignment_operator.cpp
	g++ -std=c++0x assignment_operator.cpp -o assignment_operator

compound_assignment: compound_assignment.cpp
	g++ -std=c++0x compound_assignment.cpp -o compound_assignment

conditional_ternary_operator: conditional_ternary_operator.cpp
	g++ -std=c++0x conditional_ternary_operator.cpp -o conditional_ternary_operator

clean:
	rm assignment_operator compound_assignment conditional_ternary_operator
