all: cin_and_strings stringstream

cin_and_strings: cin_and_strings.cpp
	g++ -std=c++0x cin_and_strings.cpp -o cin_and_strings

stringstream: stringstream.cpp
	g++ -std=c++0x stringstream.cpp -o stringstream

clean:
	rm cin_and_strings stringstream
