all: typed_constant_expressions


typed_constant_expressions: typed_constant_expressions.cpp
	g++ -std=c++0x typed_constant_expressions.cpp -o typed_constant_expressions

clean:
	rm typed_constant_expressions
