all: the_while_loop the_do_while_loop the_for_loop range_based_for_loop the_break_statement the_continue_statement the_goto_statement

the_while_loop: the_while_loop.cpp
	g++ -std=c++0x the_while_loop.cpp -o the_while_loop

the_do_while_loop: the_do_while_loop.cpp
	g++ -std=c++0x the_do_while_loop.cpp -o the_do_while_loop

the_for_loop: the_for_loop.cpp
	g++ -std=c++0x the_for_loop.cpp -o the_for_loop

range_based_for_loop: range_based_for_loop.cpp
	g++ -std=c++0x range_based_for_loop.cpp -o range_based_for_loop

the_break_statement: the_break_statement.cpp
	g++ -std=c++0x the_break_statement.cpp -o the_break_statement

the_continue_statement: the_continue_statement.cpp
	g++ -std=c++0x the_continue_statement.cpp -o the_continue_statement

the_goto_statement: the_goto_statement.cpp
	g++ -std=c++0x the_goto_statement.cpp -o the_goto_statement

clean:
	rm the_while_loop the_do_while_loop the_for_loop range_based_for_loop the_break_statement the_continue_statement the_goto_statement
