all: the_while_loop the_do_while_loop

the_while_loop: the_while_loop.cpp
	g++ -std=c++0x the_while_loop.cpp -o the_while_loop

the_do_while_loop: the_do_while_loop.cpp
	g++ -std=c++0x the_do_while_loop.cpp -o the_do_while_loop

clean:
	rm the_while_loop the_do_while_loop
