all: function_example void_function_example

function_example: function_example.cpp
	g++ -std=c++0x function_example.cpp -o function_example

void_function_example: void_function_example.cpp
	g++ -std=c++0x void_function_example.cpp -o void_function_example

clean:
	rm function_example void_function_example
