all: overloaded_functions function_templates

overloaded_functions: overloaded_functions.cpp
	g++ -std=c++0x overloaded_functions.cpp -o overloaded_functions

function_templates: function_templates.cpp
	g++ -std=c++0x function_templates.cpp -o function_templates

clean:
	rm overloaded_functions function_templates
