all: scopes namespaces using using01 using02 storage_classes

scopes: scopes.cpp
	g++ -std=c++0x scopes.cpp -o scopes

namespaces: namespaces.cpp
	g++ -std=c++0x namespaces.cpp -o namespaces

using: using.cpp
	g++ -std=c++0x using.cpp -o using

using01: using01.cpp
	g++ -std=c++0x using01.cpp -o using01

using02: using02.cpp
	g++ -std=c++0x using02.cpp -o using02

storage_classes: storage_classes.cpp
	g++ -std=c++0x storage_classes.cpp -o storage_classes

clean:
	rm scopes namespaces using using01 using02 storage_classes
